---
abstract: 'Utilities related to prime numbers, using GMP'
author:
  - 'Dana A Jacobsen <dana@acm.org>'
build_requires:
  Test::More: 0.45
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Prime-Util-GMP
no_index:
  directory:
    - t
    - inc
recommends:
  Math::Prime::Util: 0.024
requires:
  Carp: 0
  Exporter: 5.562
  XSLoader: 0.01
  base: 0
  perl: 5.006002
resources:
  homepage: https://github.com/danaj/Math-Prime-Util-GMP
  repository: https://github.com/danaj/Math-Prime-Util-GMP
version: 0.08
